version: '2'

services:
  gerrit:
    image: plugin-test:latest
    ports:
      - "8080:8080"
      - "29418:29418"
    networks:
      - host-net
  rabbitmq:
    image: rabbitmq:3.5.6-management
    ports:
     - "5672:5672"
     - "15672:15672"
    networks:
      - host-net
networks:
  host-net:
    driver: bridge
